### ISSUE TITLE
Camera2 support? 

### ISSUE THREAD

**Issue by kinsi55** [sh-akira/VirtualMotionCapture-en#3]
Hey,

I'm the dev of [Camera2](https://github.com/kinsi55/CS_BeatSaber_Camera2) - would it be possible to add support for it? I don't have a need for it myself but I had others ask me if this is possible.

If you want to go one step further, camera2 also has an SDK which allows you to get stuff like the position of cameras.

As far as I understand you are just reading the position and FOV from it, everything else should be compatible right?

Thanks!

**Comment by sh-akira** [comment]
There are no plans for support.
VirtualMotionCapture only supports CameraPlus.

**Comment by kinsi55** [comment]
I guess I'll implement vmc protocol into camera2 then, thank you anyways!
